[workspace]
resolver = "2"
members = [
    "ui",
    "web",
    "desktop",
    "mobile",
    "api",
]

[workspace.dependencies]
dioxus = { version = "0.7.0-alpha.0" }

# workspace
ui = { path = "ui" }
api = { path = "api" }
